title: "منصة حدوش للأدب والثقافة"
url: "https://sociologue74-collab.github.io"
baseurl: "/haddouche-literature-platform"
lang: ar
direction: rtl

collections:
  articles:
    output: true
    permalink: /articles/:name/
  writers:
    output: true
    permalink: /writers/:name.html

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article
  - scope:
      path: ""
      type: writers
    values:
      layout: writer

exclude:
  - README.md
